"""
景点初始数据
包含全球15+热门景点，涵盖亚洲、欧洲、美洲和其他地区
"""

LOCATIONS = [
    # ===== 亚洲 =====
    {
        "name": "长城",
        "name_en": "Great Wall of China",
        "continent": "asia",
        "country": "中国",
        "city": "北京",
        "category": "landmark",
        "icon": "🏯",
        "prompt_template": "at the Great Wall of China, with the ancient stone wall stretching across green mountains under a clear blue sky",
        "description": "中国古代伟大的防御工程，是世界文化遗产，绵延万里，气势磅礴。",
    },
    {
        "name": "故宫",
        "name_en": "Forbidden City",
        "continent": "asia",
        "country": "中国",
        "city": "北京",
        "category": "landmark",
        "icon": "🏛️",
        "prompt_template": "in front of the Forbidden City in Beijing, with the grand red walls and golden rooftops of the imperial palace in the background",
        "description": "中国明清两代的皇家宫殿，世界上现存规模最大的宫殿型建筑群。",
    },
    {
        "name": "富士山",
        "name_en": "Mount Fuji",
        "continent": "asia",
        "country": "日本",
        "city": "富士宫",
        "category": "nature",
        "icon": "🗻",
        "prompt_template": "near Mount Fuji in Japan, with the iconic snow-capped volcanic peak and cherry blossoms in the foreground",
        "description": "日本最高峰，海拔3776米，是日本的象征之一，以其完美的锥形轮廓闻名。",
    },
    {
        "name": "泰姬陵",
        "name_en": "Taj Mahal",
        "continent": "asia",
        "country": "印度",
        "city": "阿格拉",
        "category": "landmark",
        "icon": "🕌",
        "prompt_template": "at the Taj Mahal in Agra, India, with the magnificent white marble mausoleum and reflecting pool in the background",
        "description": "印度莫卧儿帝国皇帝为纪念亡妻而建的白色大理石陵墓，被誉为完美建筑。",
    },
    {
        "name": "吴哥窟",
        "name_en": "Angkor Wat",
        "continent": "asia",
        "country": "柬埔寨",
        "city": "暹粒",
        "category": "landmark",
        "icon": "🛕",
        "prompt_template": "at Angkor Wat in Cambodia, with the ancient temple complex and its iconic towers reflected in the surrounding moat",
        "description": "柬埔寨的国宝，世界上最大的宗教建筑群，高棉帝国的杰作。",
    },

    # ===== 欧洲 =====
    {
        "name": "埃菲尔铁塔",
        "name_en": "Eiffel Tower",
        "continent": "europe",
        "country": "法国",
        "city": "巴黎",
        "category": "landmark",
        "icon": "🗼",
        "prompt_template": "at the Eiffel Tower in Paris, France, with the iconic iron lattice tower rising against a beautiful sky",
        "description": "法国巴黎的标志性建筑，建于1889年，是世界最著名的地标之一。",
    },
    {
        "name": "罗马斗兽场",
        "name_en": "Colosseum",
        "continent": "europe",
        "country": "意大利",
        "city": "罗马",
        "category": "landmark",
        "icon": "🏟️",
        "prompt_template": "at the Colosseum in Rome, Italy, with the ancient Roman amphitheater's majestic arches in the background",
        "description": "古罗马最大的圆形竞技场，建于公元70-80年，是罗马帝国的象征。",
    },
    {
        "name": "大本钟",
        "name_en": "Big Ben",
        "continent": "europe",
        "country": "英国",
        "city": "伦敦",
        "category": "landmark",
        "icon": "🕰️",
        "prompt_template": "near Big Ben and the Houses of Parliament in London, with the iconic clock tower and the River Thames",
        "description": "伦敦的标志性建筑，位于威斯敏斯特宫北端，是英国的象征之一。",
    },
    {
        "name": "圣家堂",
        "name_en": "Sagrada Familia",
        "continent": "europe",
        "country": "西班牙",
        "city": "巴塞罗那",
        "category": "landmark",
        "icon": "⛪",
        "prompt_template": "at the Sagrada Familia in Barcelona, Spain, with Gaudi's magnificent unfinished basilica and its ornate spires",
        "description": "高迪设计的大型教堂，始建于1882年，是巴塞罗那最具代表性的建筑。",
    },

    # ===== 美洲 =====
    {
        "name": "自由女神像",
        "name_en": "Statue of Liberty",
        "continent": "americas",
        "country": "美国",
        "city": "纽约",
        "category": "landmark",
        "icon": "🗽",
        "prompt_template": "at the Statue of Liberty in New York, with the iconic green copper statue holding the torch against the city skyline",
        "description": "美国自由的象征，位于纽约港，是法国赠送给美国的礼物。",
    },
    {
        "name": "金门大桥",
        "name_en": "Golden Gate Bridge",
        "continent": "americas",
        "country": "美国",
        "city": "旧金山",
        "category": "landmark",
        "icon": "🌉",
        "prompt_template": "at the Golden Gate Bridge in San Francisco, with the iconic red suspension bridge spanning the bay with fog rolling in",
        "description": "旧金山的地标性建筑，建于1937年，是世界最著名的桥梁之一。",
    },
    {
        "name": "科罗拉多大峡谷",
        "name_en": "Grand Canyon",
        "continent": "americas",
        "country": "美国",
        "city": "亚利桑那",
        "category": "nature",
        "icon": "🏜️",
        "prompt_template": "at the Grand Canyon in Arizona, with the vast colorful canyon landscape stretching to the horizon under a dramatic sky",
        "description": "世界自然奇观，由科罗拉多河历经数百万年侵蚀而成的壮丽峡谷。",
    },

    # ===== 其他地区 =====
    {
        "name": "悉尼歌剧院",
        "name_en": "Sydney Opera House",
        "continent": "other",
        "country": "澳大利亚",
        "city": "悉尼",
        "category": "landmark",
        "icon": "🎭",
        "prompt_template": "at the Sydney Opera House in Australia, with the iconic white sail-shaped roof structures and the harbour in the background",
        "description": "澳大利亚的标志性建筑，以其独特的帆船形屋顶闻名于世。",
    },
    {
        "name": "吉萨金字塔",
        "name_en": "Pyramids of Giza",
        "continent": "other",
        "country": "埃及",
        "city": "开罗",
        "category": "landmark",
        "icon": "🔺",
        "prompt_template": "at the Pyramids of Giza in Egypt, with the ancient massive stone pyramids rising from the golden desert sands",
        "description": "古埃及法老的陵墓，世界七大奇迹中唯一现存的建筑，距今已有4500多年。",
    },
    {
        "name": "狮身人面像",
        "name_en": "Great Sphinx",
        "continent": "other",
        "country": "埃及",
        "city": "开罗",
        "category": "landmark",
        "icon": "🦁",
        "prompt_template": "at the Great Sphinx of Giza in Egypt, with the ancient limestone statue featuring a lion's body and human head, pyramids visible behind",
        "description": "古埃及的神秘守护者，狮身人面的巨型石像，与金字塔相伴数千年。",
    },
    {
        "name": "马丘比丘",
        "name_en": "Machu Picchu",
        "continent": "americas",
        "country": "秘鲁",
        "city": "库斯科",
        "category": "landmark",
        "icon": "🏔️",
        "prompt_template": "at Machu Picchu in Peru, with the ancient Incan citadel nestled among misty green mountain peaks",
        "description": "印加帝国的失落之城，建于15世纪，坐落在安第斯山脉的高峰之上。",
    },
    {
        "name": "圣托里尼",
        "name_en": "Santorini",
        "continent": "europe",
        "country": "希腊",
        "city": "圣托里尼",
        "category": "city",
        "icon": "🏘️",
        "prompt_template": "in Santorini, Greece, with the iconic white-washed buildings and blue-domed churches overlooking the deep blue Aegean Sea",
        "description": "希腊爱琴海上的火山岛，以蓝白相间的建筑和绝美日落闻名。",
    },
    {
        "name": "尼亚加拉瀑布",
        "name_en": "Niagara Falls",
        "continent": "americas",
        "country": "加拿大",
        "city": "尼亚加拉",
        "category": "nature",
        "icon": "💧",
        "prompt_template": "at Niagara Falls, with the massive horseshoe waterfall cascading down and mist rising into the sky",
        "description": "世界三大跨国瀑布之一，横跨美国与加拿大边境，气势壮观。",
    },
]


def get_locations():
    """返回所有景点数据"""
    return LOCATIONS
